name: Deploy APIM Infrastructure and Application

on:
  workflow_dispatch:
    inputs:
      subscriptionId:
        description: 'Azure Subscription ID'
        required: true
      resourceGroup:
        description: 'Resource Group name'
        required: true
        default: 'apim-demo-rg'
      location:
        description: 'Azure region'
        required: true
        default: 'eastus'
      environment:
        description: 'Environment (dev, test, prod)'
        required: true
        default: 'dev'
      namePrefix:
        description: 'Name prefix for resources'
        required: true
        default: 'apim-demo'
      adminEmail:
        description: 'Admin email for APIM'
        required: true
        default: 'admin@example.com'
      orgName:
        description: 'Organization name for APIM'
        required: true
        default: 'APIM Demo Organization'
      apimSku:
        description: 'APIM SKU (Developer, Basic, Standard, Premium)'
        required: true
        default: 'Developer'
        type: choice
        options:
          - Developer
          - Basic
          - Standard
          - Premium

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Azure CLI
        uses: azure/setup-azure-cli@v1

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Resource Group
        run: |
          az group create --name "${{ github.event.inputs.resourceGroup }}" --location "${{ github.event.inputs.location }}"

      - name: Deploy Bicep template
        working-directory: APIMDemo/infra
        run: |
          az deployment group create \
            --resource-group "${{ github.event.inputs.resourceGroup }}" \
            --template-file main.bicep \
            --parameters location="${{ github.event.inputs.location }}" \
                       environment="${{ github.event.inputs.environment }}" \
                       namePrefix="${{ github.event.inputs.namePrefix }}" \
                       apimAdminEmail="${{ github.event.inputs.adminEmail }}" \
                       apimOrgName="${{ github.event.inputs.orgName }}" \
                       apimSku="${{ github.event.inputs.apimSku }}"
        # Setup .NET using .NET SDK
      - name: Setup .NET
        run: |
          echo "Installing .NET SDK"
          wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
          chmod +x ./dotnet-install.sh
          ./dotnet-install.sh --version 9.0.100-preview.4.24260.5 --install-dir ~/.dotnet
          echo "$HOME/.dotnet" >> $GITHUB_PATH
          echo "DOTNET_ROOT=$HOME/.dotnet" >> $GITHUB_ENV
          
      # Build and publish .NET application
      - name: Build and publish
        run: |
          dotnet publish APIMDemo/APIMDemo.csproj -c Release -o ./publish
      
      # Deploy to Azure App Service using Azure CLI
      - name: Deploy to Azure App Service
        run: |
          APP_NAME="${{ github.event.inputs.namePrefix }}-${{ github.event.inputs.environment }}-api"
          echo "Deploying to App Service: $APP_NAME"
          
          # Create zip deployment package
          cd publish
          zip -r ../app-deploy.zip .
          cd ..
          
          # Deploy to App Service
          az webapp deployment source config-zip \
            --resource-group "${{ github.event.inputs.resourceGroup }}" \
            --name "$APP_NAME" \
            --src "app-deploy.zip"